version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8234:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.:/var/www:delegated
    depends_on:
      - php

  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./.:/var/www:delegated
      - ~/.composer:/root/.composer
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    env_file:
      - .env
    environment:
      - DOCKER_DEV=true
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb/config:/data/configdb
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example